apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayline-website
  namespace: wayline-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wayline
  template:
    metadata:
      labels:
        app: wayline
    spec:
      containers:
      - name: wayline
        image: dkhan573/wayline-website:latest
        ports:
        - containerPort: 80   # matches Nginx container
