apiVersion: v1
kind: Service
metadata:
  name: wayline-service
  namespace: wayline-website
spec:
  type: NodePort
  selector:
    app: wayline
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
